"""Complete the CosQA valid-split HyDE run using verified shared E5 vectors.

HyDE hypotheses are generated by the notebook with the pinned Transformers
runtime. Corpus embeddings can be reused across qrels splits because they
depend on the immutable corpus and E5 controls, not on qrels. This script
checks those controls and requires exact equality with the independent valid
E5 candidate rankings before accepting the reused vectors.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import sys
import time
from typing import Any, Mapping

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from run_benchmark_notebook import require_pinned_runtime

from e5_baseline import (  # noqa: E402
    evaluate_ndcg_at_10,
    load_cosqa,
    load_valid_embedding_cache,
    load_valid_json_cache,
    rank_with_faiss,
    save_embedding_cache,
    save_json_cache,
    select_run_data,
    set_seed,
    sha256_ids,
    write_result_artifacts,
)
from e5_hyde import (  # noqa: E402
    E5Encoder,
    HyDEConfig,
    build_expanded_queries,
    build_hyde_result,
    expected_hyde_cache_metadata,
    hyde_cache_paths,
    hyde_run_identity,
    validate_hypotheses,
)
from e5_hyde_rerank import candidate_contract, reciprocal_rank_fusion  # noqa: E402


VALIDATION_DIR = PROJECT_ROOT / "artifacts" / "e5_hyde_rerank" / "validation"
EXPECTED_E5_RANKINGS = VALIDATION_DIR / "rerank_depth1000" / "e5_rankings.json"
CORPUS_CACHE_ROOT = PROJECT_ROOT / "artifacts" / "e5_hyde_rerank" / "cache"


def _read_json(path: Path) -> Any:
    with path.open(encoding="utf-8") as stream:
        return json.load(stream)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _relative(path: Path) -> str:
    resolved = path.resolve() if path.is_absolute() else (PROJECT_ROOT / path).resolve()
    return str(resolved.relative_to(PROJECT_ROOT))


def _assert_complete_rankings(
    name: str,
    rankings: Mapping[str, Mapping[str, float]],
    query_ids: set[str],
    depth: int,
) -> None:
    if set(rankings) != query_ids:
        raise ValueError(f"{name} does not cover the complete valid qrels query set")
    if any(len(candidates) != depth for candidates in rankings.values()):
        raise ValueError(f"{name} must contain exactly {depth} candidates per query")


def _compatible_corpus_cache(
    metadata: Mapping[str, Any],
    *,
    config: HyDEConfig,
    corpus_ids: list[str],
    environment: Mapping[str, Any],
) -> None:
    source_config = metadata.get("config", {})
    for key, expected in (
        ("dataset_id", config.dataset_id),
        ("dataset_revision", config.dataset_revision),
        ("corpus_config", config.corpus_config),
        ("corpus_split", config.corpus_split),
        ("model_id", config.model_id),
        ("model_revision", config.model_revision),
        ("passage_prefix", config.passage_prefix),
        ("max_seq_length", config.max_seq_length),
        ("normalize_embeddings", config.normalize_embeddings),
        ("batch_size", config.batch_size),
        ("device", config.device),
    ):
        if source_config.get(key) != expected:
            raise ValueError(f"shared corpus cache has incompatible {key}")
    if metadata.get("kind") != "corpus_embeddings":
        raise ValueError("shared cache is not a corpus embedding cache")
    if metadata.get("count") != len(corpus_ids):
        raise ValueError("shared corpus cache has the wrong row count")
    if metadata.get("ids_sha256") != sha256_ids(corpus_ids):
        raise ValueError("shared corpus cache uses a different ordered corpus ID list")

    source_environment = metadata.get("execution_environment", {})
    environment_keys = (
        "python",
        "platform",
        "processor",
        "device",
        "packages",
        "torch_version",
        "torch_default_dtype",
        "torch_num_threads",
        "torch_deterministic_algorithms",
        "torch_float32_matmul_precision",
        "torch_cuda_matmul_allow_tf32",
        "cuda_available",
        "cuda_device_count",
        "cuda_device_name",
    )
    mismatches = [
        key for key in environment_keys if source_environment.get(key) != environment.get(key)
    ]
    if mismatches:
        raise ValueError(
            "shared corpus cache has incompatible execution controls: "
            + ", ".join(mismatches)
        )


def _find_shared_corpus_cache(
    *,
    config: HyDEConfig,
    corpus_ids: list[str],
    environment: Mapping[str, Any],
) -> tuple[Path, Path, dict[str, Any]]:
    candidates = sorted(CORPUS_CACHE_ROOT.glob("*/corpus_embeddings.metadata.json"))
    failures: list[str] = []
    for metadata_path in candidates:
        try:
            metadata = _read_json(metadata_path)
            _compatible_corpus_cache(
                metadata,
                config=config,
                corpus_ids=corpus_ids,
                environment=environment,
            )
        except (OSError, ValueError, json.JSONDecodeError) as exc:
            failures.append(f"{metadata_path.parent.name}: {exc}")
            continue
        data_path = metadata_path.with_name("corpus_embeddings.npy")
        if data_path.is_file():
            return data_path, metadata_path, metadata
    raise FileNotFoundError(
        "no corpus embedding cache matches the complete E5/runtime contract"
        + ("; checked: " + "; ".join(failures) if failures else "")
    )


def main() -> None:
    require_pinned_runtime()
    # Continue the completed 0.50/0.50 valid run whose generation and ranking
    # caches are inputs to the selector. The selected 0.65/0.35 weights are
    # recorded separately and applied by the validation selector/test runner.
    config = HyDEConfig(
        run_mode="benchmark", qrels_split="valid", fusion_weights=(0.5, 0.5)
    )
    import torch

    torch.set_num_threads(8)
    set_seed(config.seed)
    initial_environment = __import__("e5_hyde").environment_metadata(
        config, repo_root=PROJECT_ROOT
    )
    initial_environment["model_revisions"] = {
        "e5": config.model_revision,
        "hyde": config.generator_revision,
    }

    data = load_cosqa(config)
    run_data = select_run_data(data, config)
    if (
        len(run_data.queries) != 500
        or len(run_data.qrels) != 500
        or len(run_data.corpus) != 20604
        or len(run_data.queries) != len(data.queries)
    ):
        raise RuntimeError("expected the complete 500-query valid split and 20,604-document corpus")

    notebook_path = PROJECT_ROOT / "notebooks" / "e5_hyde_experiment.ipynb"
    current_notebook_sha256 = _sha256(notebook_path)
    previous_result_path = PROJECT_ROOT / "artifacts" / "e5_hyde" / "result.json"
    previous_result = _read_json(previous_result_path) if previous_result_path.is_file() else {}
    notebook_hash_candidates = [
        previous_result.get("notebook_sha256"),
        current_notebook_sha256,
    ]
    notebook_sha256 = None
    identity = None
    paths = None
    environment_for_identity = __import__("e5_hyde").environment_metadata(
        config, repo_root=PROJECT_ROOT
    )
    for candidate_notebook_sha256 in dict.fromkeys(
        value for value in notebook_hash_candidates if value
    ):
        candidate_identity = hyde_run_identity(
            config,
            repo_root=PROJECT_ROOT,
            notebook_sha256=candidate_notebook_sha256,
            environment=environment_for_identity,
        )
        candidate_paths = hyde_cache_paths(config, candidate_identity)
        if candidate_paths["hypotheses"].is_file() and candidate_paths["hypotheses_metadata"].is_file():
            notebook_sha256 = candidate_notebook_sha256
            identity = candidate_identity
            paths = candidate_paths
            break
    if identity is None or paths is None or notebook_sha256 is None:
        raise FileNotFoundError(
            "no complete real HyDE generation cache matches the current valid-run controls"
        )
    query_ids = list(run_data.queries)
    corpus_ids = list(run_data.corpus)
    hypotheses_source = paths["hypotheses"]
    hypotheses_metadata_path = paths["hypotheses_metadata"]
    hypotheses_cache = _read_json(hypotheses_source)
    hypothesis_metadata = _read_json(hypotheses_metadata_path)
    expected_hypothesis_metadata = expected_hyde_cache_metadata(
        config,
        identity=identity,
        kind="hypotheses",
        ids=query_ids,
        repo_root=PROJECT_ROOT,
        notebook_sha256=notebook_sha256,
        environment=__import__("e5_hyde").environment_metadata(config, repo_root=PROJECT_ROOT),
    )
    if hypothesis_metadata != expected_hypothesis_metadata:
        raise ValueError("cached valid hypotheses do not match the pinned run identity")
    if set(hypotheses_cache) != {"hypotheses", "fallback_query_ids"}:
        raise ValueError("cached hypothesis artifact has an unknown schema")
    hypotheses = validate_hypotheses(run_data.queries, hypotheses_cache["hypotheses"])
    fallback_query_ids = list(hypotheses_cache["fallback_query_ids"])
    initial_environment["hyde_fallback_query_count"] = len(fallback_query_ids)

    expanded_queries = build_expanded_queries(
        run_data.queries,
        hypotheses,
        strategy=config.combination_strategy,
    )
    expanded_metadata = expected_hyde_cache_metadata(
        config,
        identity=identity,
        kind="expanded_queries",
        ids=query_ids,
        repo_root=PROJECT_ROOT,
        notebook_sha256=notebook_sha256,
        environment=initial_environment,
    )
    if _read_json(paths["expanded_queries_metadata"]) != expanded_metadata:
        raise ValueError("cached expanded-query metadata does not match the pinned run identity")
    if _read_json(paths["expanded_queries"]) != expanded_queries:
        raise ValueError("cached expanded queries do not match the validated hypotheses")
    revisions = {
        "e5": config.model_revision,
        "hyde": config.generator_revision,
    }
    initial_environment["model_revisions"] = revisions

    source_data_path, source_metadata_path, source_metadata = _find_shared_corpus_cache(
        config=config,
        corpus_ids=corpus_ids,
        environment=initial_environment,
    )
    source_sha256 = _sha256(source_data_path)
    corpus_metadata = expected_hyde_cache_metadata(
        config,
        identity=identity,
        kind="corpus_embeddings",
        ids=corpus_ids,
        repo_root=PROJECT_ROOT,
        notebook_sha256=notebook_sha256,
        environment=initial_environment,
    )
    corpus_metadata["derived_from_cache"] = {
        "identity": source_metadata.get("identity"),
        "metadata_path": _relative(source_metadata_path),
        "metadata_sha256": _sha256(source_metadata_path),
        "embeddings_path": _relative(source_data_path),
        "embeddings_sha256": source_sha256,
        "reuse_basis": "same immutable ordered corpus, E5 revision/preprocessing, runtime, and execution controls",
    }
    corpus_embeddings = load_valid_embedding_cache(
        paths["corpus_embeddings"], paths["corpus_metadata"], corpus_metadata
    )
    if corpus_embeddings is None:
        corpus_embeddings = np.load(source_data_path, allow_pickle=False)
        if (
            corpus_embeddings.ndim != 2
            or corpus_embeddings.shape[0] != len(corpus_ids)
            or not np.isfinite(corpus_embeddings).all()
        ):
            raise ValueError("shared corpus embedding cache has invalid shape or values")
        save_embedding_cache(
            paths["corpus_embeddings"], paths["corpus_metadata"], corpus_embeddings, corpus_metadata
        )

    ranking_ids = query_ids + ["__corpus__"] + corpus_ids
    ranking_seconds = 0.0
    query_encoding_seconds = 0.0
    encoder: E5Encoder | None = None
    expanded_embedding_metadata = expected_hyde_cache_metadata(
        config,
        identity=identity,
        kind="query_embeddings",
        ids=query_ids,
        repo_root=PROJECT_ROOT,
        notebook_sha256=notebook_sha256,
        environment=initial_environment,
    )
    original_embedding_metadata = expected_hyde_cache_metadata(
        config,
        identity=identity,
        kind="original_query_embeddings",
        ids=query_ids,
        repo_root=PROJECT_ROOT,
        notebook_sha256=notebook_sha256,
        environment=initial_environment,
    )
    expanded_embeddings = load_valid_embedding_cache(
        paths["query_embeddings"], paths["query_metadata"], expanded_embedding_metadata
    )
    original_embeddings = load_valid_embedding_cache(
        paths["original_query_embeddings"],
        paths["original_query_metadata"],
        original_embedding_metadata,
    )
    if expanded_embeddings is None or original_embeddings is None:
        encoder = E5Encoder(config)
        query_started = time.perf_counter()
        if expanded_embeddings is None:
            expanded_embeddings = encoder.encode_queries(
                [expanded_queries[query_id] for query_id in query_ids]
            )
        if original_embeddings is None:
            original_embeddings = encoder.encode_queries(
                [run_data.queries[query_id] for query_id in query_ids]
            )
        query_encoding_seconds = time.perf_counter() - query_started

    original_ranking_metadata = expected_hyde_cache_metadata(
        config,
        identity=identity,
        kind="original_rankings",
        ids=ranking_ids,
        repo_root=PROJECT_ROOT,
        notebook_sha256=notebook_sha256,
        environment=initial_environment,
    )
    hyde_ranking_metadata = expected_hyde_cache_metadata(
        config,
        identity=identity,
        kind="rankings",
        ids=ranking_ids,
        repo_root=PROJECT_ROOT,
        notebook_sha256=notebook_sha256,
        environment=initial_environment,
    )
    original_rankings = load_valid_json_cache(
        paths["original_rankings"], paths["original_rankings_metadata"], original_ranking_metadata
    )
    hyde_rankings = load_valid_json_cache(
        paths["rankings"], paths["rankings_metadata"], hyde_ranking_metadata
    )
    if original_rankings is None or hyde_rankings is None:
        if encoder is None:
            encoder = E5Encoder(config)
        ranking_started = time.perf_counter()
        if original_rankings is None:
            original_rankings = rank_with_faiss(
                original_embeddings,
                corpus_embeddings,
                query_ids,
                corpus_ids,
                top_k=config.candidate_depth,
            )
        if hyde_rankings is None:
            hyde_rankings = rank_with_faiss(
                expanded_embeddings,
                corpus_embeddings,
                query_ids,
                corpus_ids,
                top_k=config.candidate_depth,
            )
        ranking_seconds = time.perf_counter() - ranking_started
    reference_rankings = _read_json(EXPECTED_E5_RANKINGS)
    _assert_complete_rankings(
        "computed validation E5 rankings", original_rankings, set(query_ids), config.candidate_depth
    )
    _assert_complete_rankings(
        "active reranker E5 rankings", reference_rankings, set(query_ids), config.candidate_depth
    )
    if original_rankings != reference_rankings:
        raise RuntimeError(
            "cross-split corpus reuse failed exact E5 ranking parity; refusing the HyDE result"
        )

    for path, metadata_path, ranking, ranking_metadata in (
        (paths["rankings"], paths["rankings_metadata"], hyde_rankings, hyde_ranking_metadata),
        (
            paths["original_rankings"],
            paths["original_rankings_metadata"],
            original_rankings,
            original_ranking_metadata,
        ),
    ):
        if not path.is_file() or load_valid_json_cache(path, metadata_path, ranking_metadata) is None:
            save_json_cache(path, metadata_path, ranking, ranking_metadata)

    for path, metadata_path, embeddings, embedding_metadata in (
        (paths["query_embeddings"], paths["query_metadata"], expanded_embeddings, expanded_embedding_metadata),
        (
            paths["original_query_embeddings"],
            paths["original_query_metadata"],
            original_embeddings,
            original_embedding_metadata,
        ),
    ):
        if not path.is_file() or load_valid_embedding_cache(path, metadata_path, embedding_metadata) is None:
            save_embedding_cache(path, metadata_path, embeddings, embedding_metadata)

    fusion_started = time.perf_counter()
    fused_rankings = reciprocal_rank_fusion(
        [original_rankings, hyde_rankings],
        weights=config.fusion_weights,
        top_k=config.candidate_depth,
        rrf_k=config.rrf_k,
    )
    fusion_seconds = time.perf_counter() - fusion_started
    fused_metadata = expected_hyde_cache_metadata(
        config,
        identity=identity,
        kind="fused_rankings",
        ids=ranking_ids,
        repo_root=PROJECT_ROOT,
        notebook_sha256=notebook_sha256,
        environment=initial_environment,
    )
    if load_valid_json_cache(
        paths["fused_rankings"], paths["fused_rankings_metadata"], fused_metadata
    ) is None:
        save_json_cache(
            paths["fused_rankings"], paths["fused_rankings_metadata"], fused_rankings, fused_metadata
        )

    evaluation_started = time.perf_counter()
    baseline_metric = evaluate_ndcg_at_10(run_data.qrels, original_rankings, cutoff=10)
    raw_metric = evaluate_ndcg_at_10(run_data.qrels, hyde_rankings, cutoff=10)
    fused_metric = evaluate_ndcg_at_10(run_data.qrels, fused_rankings, cutoff=10)
    evaluation_seconds = time.perf_counter() - evaluation_started
    result = build_hyde_result(
        config,
        data,
        run_data,
        fused_metric,
        identity=identity,
        environment=initial_environment,
        timings={
            "generation": None,
            "corpus_encoding": 0.0,
            "query_encoding": query_encoding_seconds if query_encoding_seconds > 0 else None,
            "ranking": ranking_seconds if ranking_seconds > 0 else None,
            "original_ranking": ranking_seconds if ranking_seconds > 0 else None,
            "rrf_fusion": fusion_seconds,
            "evaluation": evaluation_seconds,
        },
        hypothesis_count=len(hypotheses),
        repo_root=PROJECT_ROOT,
        notebook_sha256=notebook_sha256,
    )
    result["cache_paths"] = {name: str(path) for name, path in paths.items()}
    result["component_diagnostics"] = {
        "e5_baseline_ndcg_at_10": baseline_metric["ndcg_at_10"],
        "e5_hyde_raw_ndcg_at_10": raw_metric["ndcg_at_10"],
        "e5_hyde_delta_vs_e5": fused_metric["ndcg_at_10"] - baseline_metric["ndcg_at_10"],
    }
    result["candidate_contract"] = {
        "e5": candidate_contract(original_rankings),
        "e5_hyde_raw": candidate_contract(hyde_rankings),
        "e5_hyde": {
            **candidate_contract(fused_rankings),
            "pool_policy": "union_of_e5_and_hyde_top_k_truncated_to_candidate_depth",
        },
    }
    result["baseline_parity"] = {
        "reference": "artifacts/e5_hyde_rerank/validation/rerank_depth1000/e5_rankings.json",
        "exact_ordered_rankings_match": True,
        "checked_queries": len(query_ids),
        "candidate_depth": config.candidate_depth,
    }
    result["artifact_provenance"]["execution_entrypoint"] = (
        "code-retrieval/scripts/run_hyde_validation.py"
    )
    result["artifact_provenance"]["continued_from_same_identity_notebook"] = True
    result["artifact_provenance"]["reused_corpus_embeddings"] = True
    result["artifact_provenance"]["source_corpus_cache_identity"] = source_metadata.get("identity")
    result["artifact_provenance"]["ranking_baseline_exactly_matches_reranker_validation"] = True
    result["execution_script_sha256"] = _sha256(Path(__file__).resolve())
    result["source_code_sha256"] = {
        str(path.relative_to(PROJECT_ROOT)): _sha256(path)
        for path in (
            PROJECT_ROOT / "src" / "e5_hyde.py",
            PROJECT_ROOT / "src" / "e5_baseline.py",
            PROJECT_ROOT / "src" / "e5_hyde_rerank.py",
        )
    }
    result["source_artifacts"] = {
        "hypotheses": {
            "path": _relative(hypotheses_source),
            "sha256": _sha256(hypotheses_source),
            "metadata_path": _relative(hypotheses_metadata_path),
            "metadata_sha256": _sha256(hypotheses_metadata_path),
        },
        "corpus_embeddings": corpus_metadata["derived_from_cache"],
        "e5_validation_reference": {
            "path": str(EXPECTED_E5_RANKINGS.relative_to(PROJECT_ROOT)),
            "sha256": _sha256(EXPECTED_E5_RANKINGS),
        },
        "e5_original_rankings": {
            "path": _relative(paths["original_rankings"]),
            "sha256": _sha256(paths["original_rankings"].resolve()),
            "metadata_path": _relative(paths["original_rankings_metadata"]),
            "metadata_sha256": _sha256(paths["original_rankings_metadata"].resolve()),
        },
        "hyde_query_plus_rankings": {
            "path": _relative(paths["rankings"]),
            "sha256": _sha256(paths["rankings"].resolve()),
            "metadata_path": _relative(paths["rankings_metadata"]),
            "metadata_sha256": _sha256(paths["rankings_metadata"].resolve()),
        },
        "fused_rankings": {
            "path": _relative(paths["fused_rankings"]),
            "sha256": _sha256(paths["fused_rankings"].resolve()),
            "metadata_path": _relative(paths["fused_rankings_metadata"]),
            "metadata_sha256": _sha256(paths["fused_rankings_metadata"].resolve()),
        },
        "query_embeddings": {
            "expanded": {
                "path": _relative(paths["query_embeddings"]),
                "sha256": _sha256(paths["query_embeddings"].resolve()),
            },
            "original": {
                "path": _relative(paths["original_query_embeddings"]),
                "sha256": _sha256(paths["original_query_embeddings"].resolve()),
            },
        },
    }
    result["source_artifacts"]["corpus_embeddings"] = corpus_metadata["derived_from_cache"]
    result["cache_metadata"] = {
        "hypotheses": hypothesis_metadata,
        "corpus": corpus_metadata,
        "queries": expected_hyde_cache_metadata(
            config,
            identity=identity,
            kind="query_embeddings",
            ids=query_ids,
            repo_root=PROJECT_ROOT,
            notebook_sha256=notebook_sha256,
            environment=initial_environment,
        ),
        "original_queries": expected_hyde_cache_metadata(
            config,
            identity=identity,
            kind="original_query_embeddings",
            ids=query_ids,
            repo_root=PROJECT_ROOT,
            notebook_sha256=notebook_sha256,
            environment=initial_environment,
        ),
        "rankings": expected_hyde_cache_metadata(
            config,
            identity=identity,
            kind="rankings",
            ids=ranking_ids,
            repo_root=PROJECT_ROOT,
            notebook_sha256=notebook_sha256,
            environment=initial_environment,
        ),
        "original_rankings": expected_hyde_cache_metadata(
            config,
            identity=identity,
            kind="original_rankings",
            ids=ranking_ids,
            repo_root=PROJECT_ROOT,
            notebook_sha256=notebook_sha256,
            environment=initial_environment,
        ),
        "fused_rankings": fused_metadata,
    }
    artifact_paths = write_result_artifacts(
        config,
        result,
        metadata={"result": result, "cache_metadata": result["cache_metadata"]},
    )
    print(json.dumps({
        "cache_identity": identity,
        "baseline_ndcg_at_10": baseline_metric["ndcg_at_10"],
        "raw_hyde_ndcg_at_10": raw_metric["ndcg_at_10"],
        "fused_ndcg_at_10": fused_metric["ndcg_at_10"],
        "baseline_parity": result["baseline_parity"],
        "source_corpus_cache_identity": source_metadata.get("identity"),
        "artifact_paths": artifact_paths,
    }, indent=2))


if __name__ == "__main__":
    main()
